# Generated by Django 3.1.5 on 2021-02-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifeoluwaniscrumy', '0002_auto_20210208_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrumyhistory',
            old_name='moved_fro',
            new_name='moved_from',
        ),
    ]
